import { CheckCircle2, FileSignature, Scale, ShieldAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { humanDecisionCanSign } from "@/lib/protocol";
import type { ContractState } from "@/lib/case-model";

type Checklist = keyof ContractState["humanDecision"]["checklist"];
type Props = {
  state: ContractState; busy: boolean; notice: string;
  toggleSettlementConsent: (party: "supplier" | "customer") => void; requestSettlement: () => void;
  respondSettlement: (party: "supplier" | "customer", response: "accept" | "decline") => void;
  updatePreliminary: (value: string) => void; runDetermination: (mode: "illustrative" | "live") => void;
  updateDecision: (field: "status" | "rationale", value: string) => void;
  toggleChecklist: (field: Checklist) => void; signDecision: () => void;
};

export function DisputePreview({ state, busy, notice, toggleSettlementConsent, requestSettlement, respondSettlement, updatePreliminary, runDetermination, updateDecision, toggleChecklist, signDecision }: Props) {
  const simulationReady = state.lifecycleStatus === "appointment_simulated";
  const proposal = state.settlement.proposal;
  return <>
    <div className="page-intro"><span>Stage 5 · later synthetic dispute</span><h1>Apply the acknowledged simulation protocol, then preserve human control.</h1><p>The synthetic dispute is bound to the exact manifest hash. Settlement remains sealed. Every determination and human decision record is provisional, non-operative, and without legal effect.</p></div>
    {!simulationReady && <div className="warning"><ShieldAlert size={18} /><div><strong>No simulated appointment record</strong><p>Complete the manifest acknowledgement and integrity-verified simulated ceremony before opening this synthetic dispute.</p></div></div>}
    <div className={!simulationReady ? "stage-disabled" : ""}>
      <Card className="dispute-record"><div className="finding-top"><div><Badge tone="red">Shared merits record</Badge><h2>Later SaaS outage</h2></div><span className="version">{state.dispute.id}</span></div><div className="position-grid"><div><small>Customer claim</small><p>{state.dispute.claim}</p></div><div><small>Supplier defence</small><p>{state.dispute.defence}</p></div></div><div className="calibration-columns"><div><small>Shared evidence</small><ul>{state.dispute.sharedEvidence.map((item) => <li key={item}>{item}</li>)}</ul></div><div><small>Objections and missing evidence</small><ul>{[...state.dispute.objections, ...state.dispute.missingEvidence].map((item) => <li key={item}>{item}</li>)}</ul></div></div></Card>
      <Card className="settlement-card"><Badge tone="blue">Optional · sealed simulation track</Badge><h2>Settlement Facilitation</h2><p>This is separate from alignment and merits reasoning. It activates only with simulated bilateral consent and uses the shared synthetic record.</p><div className="confirm-row"><span>Bilateral simulation activation</span><div>{(["supplier", "customer"] as const).map((party) => <Button key={party} disabled={!simulationReady} variant={state.settlement.consents[party] ? "secondary" : "ghost"} onClick={() => toggleSettlementConsent(party)}>{state.settlement.consents[party] && <CheckCircle2 size={14} />} {party}</Button>)}</div></div><Button disabled={!state.settlement.consents.supplier || !state.settlement.consents.customer || Boolean(proposal)} onClick={requestSettlement}>Generate non-binding proposal</Button>
        {proposal && <div className="sealed-proposal"><Badge tone="red">Sealed from merits</Badge><h3>{proposal.label}</h3><ul>{proposal.terms.map((term) => <li key={term}>{term}</li>)}</ul><p>{proposal.basis}</p><div className="response-grid">{(["supplier", "customer"] as const).map((party) => <div key={party}><strong>{party}</strong><Button variant="secondary" onClick={() => respondSettlement(party, "accept")}>Accept</Button><Button variant="ghost" onClick={() => respondSettlement(party, "decline")}>Decline</Button><small>{state.settlement.responses[party]}</small></div>)}</div></div>}
        {state.settlement.status === "not_settled" && <p className="notice">Settlement facilitation ended without settlement. Proposal content remains outside the merits record.</p>}
      </Card>
      <Card className="human-preassessment"><Badge>Fictional human assessment · simulation</Badge><h2>Record an initial view before revealing the protocol proposal.</h2><textarea disabled={!simulationReady} value={state.humanDecision.preliminaryAssessment} onChange={(event) => updatePreliminary(event.target.value)} placeholder="Fictional arbitrator’s preliminary issue assessment…" /><div className="action-row"><Button variant="secondary" disabled={!simulationReady || state.settlement.status === "settled" || busy || !state.humanDecision.preliminaryAssessment.trim()} onClick={() => runDetermination("illustrative")}>View illustrative example</Button><Button disabled={!simulationReady || state.settlement.status === "settled" || busy || !state.humanDecision.preliminaryAssessment.trim()} onClick={() => runDetermination("live")}>{busy ? "Running…" : "Run live execution"}</Button></div>{notice && <p className="notice" role="status">{notice}</p>}</Card>
      {state.proposedDetermination && <Card className="determination-card"><Badge tone="blue">Proposed determination · no independent legal effect</Badge><h2>{state.proposedDetermination.proposedDisposition}</h2><p>{state.proposedDetermination.reasoningSummary}</p><div className="calibration-columns"><div><small>Findings</small><ul>{state.proposedDetermination.findings.map((item) => <li key={item}>{item}</li>)}</ul></div><div><small>Uncertainty and escalation</small><ul>{[...state.proposedDetermination.uncertainty, ...state.proposedDetermination.escalationFlags].map((item) => <li key={item}>{item}</li>)}</ul></div></div><span className="version">Bound to {state.proposedDetermination.appointmentHash}</span></Card>}
      {state.proposedDetermination && <Card className="human-decision"><Badge tone="red">Fictional human control · no legal effect</Badge><h2>Adopt, modify, or reject in the simulation.</h2><div className="option-row">{(["adopted", "modified", "rejected"] as const).map((status) => <button key={status} className={state.humanDecision.status === status ? "option selected" : "option"} onClick={() => updateDecision("status", status)}><span>{status}</span><small>The fictional record preserves independent reasoning control.</small></button>)}</div><label className="clause-editor"><span>Independent simulated rationale</span><textarea value={state.humanDecision.rationale} onChange={(event) => updateDecision("rationale", event.target.value)} /></label><div className="review-checklist">{(Object.keys(state.humanDecision.checklist) as Checklist[]).map((field) => <label key={field} className="checkline"><input type="checkbox" checked={state.humanDecision.checklist[field]} onChange={() => toggleChecklist(field)} /> {field.replace(/([A-Z])/g, " $1")}</label>)}</div><Button disabled={!humanDecisionCanSign(state)} onClick={signDecision}><FileSignature size={15} /> Record simulated human decision</Button></Card>}
      {state.humanDecision.simulatedSignature && <div className="result success final-award"><Badge tone="green">Simulated human decision · non-operative</Badge><strong>{state.humanDecision.status}</strong><span>{state.humanDecision.simulatedSignature}</span><p><Scale size={14} /> Fictional review record only · no production signature, award, or legal effect.</p></div>}
    </div>
  </>;
}
